// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyqFK7-FfCyPgyDNLNS-Lw_5YlyxJqtKY',
    appId: '1:500362850823:web:dc2fe156bfe08d19f030a2',
    messagingSenderId: '500362850823',
    projectId: 'thefinalwhistle-5a7cb',
    authDomain: 'thefinalwhistle-5a7cb.firebaseapp.com',
    storageBucket: 'thefinalwhistle-5a7cb.appspot.com',
    measurementId: 'G-JGE6D4R4QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQkTwzHd1F9Up2-x3G1x8BLql9cQWGoDg',
    appId: '1:500362850823:android:24a21dc242f5c610f030a2',
    messagingSenderId: '500362850823',
    projectId: 'thefinalwhistle-5a7cb',
    storageBucket: 'thefinalwhistle-5a7cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXGdVrTNwIqnTDRm2wLPoB3eV_yRbJuQ',
    appId: '1:500362850823:ios:520dba71ca3fac6df030a2',
    messagingSenderId: '500362850823',
    projectId: 'thefinalwhistle-5a7cb',
    storageBucket: 'thefinalwhistle-5a7cb.appspot.com',
    iosBundleId: 'com.example.theFinalWhistle',
  );
}
